// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// All HTTP traffic (auth, rest, storage, functions) is proxied through
// api.vanshmala.in via Vercel rewrites — the raw supabase.co URL is never
// visible to users in browser network devtools for these calls.
const SUPABASE_URL = "https://api.vanshmala.in";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuZ2ZkY2JjY25ndWZ0eHplY3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4OTEzMjEsImV4cCI6MjA4NjQ2NzMyMX0.gnMlusI3u02cuszKFFL7Yb_rm1exC7LT8Tev4loSX7E";

// Vercel CANNOT proxy WebSocket (WSS) traffic, so Realtime must connect
// directly to the raw supabase.co URL. We bypass the SDK's auto-derived WSS
// URL (which would be wss://api.vanshmala.in/... and would fail) by
// overriding supabase.realtime.endPoint right after client creation.
const SUPABASE_RAW_URL = "https://qngfdcbccnguftxzecwq.supabase.co";
const REALTIME_WSS_URL = SUPABASE_RAW_URL.replace(/^https?:\/\//, (m) =>
  m.startsWith('https') ? 'wss://' : 'ws://'
) + '/realtime/v1/websocket';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Override the realtime WebSocket endpoint to bypass Vercel's WSS limitation.
// supabase.realtime.endPoint is the raw WSS URL the RealtimeClient dials.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
(supabase.realtime as any).endPoint = REALTIME_WSS_URL;
