// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qngfdcbccnguftxzecwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuZ2ZkY2JjY25ndWZ0eHplY3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4OTEzMjEsImV4cCI6MjA4NjQ2NzMyMX0.gnMlusI3u02cuszKFFL7Yb_rm1exC7LT8Tev4loSX7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});